#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseElectric.DataLayer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ElectricWarehouse")]
	public partial class LinqDataLayerDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCU_Customer(CU_Customer instance);
    partial void UpdateCU_Customer(CU_Customer instance);
    partial void DeleteCU_Customer(CU_Customer instance);
    partial void InsertWO_Worker(WO_Worker instance);
    partial void UpdateWO_Worker(WO_Worker instance);
    partial void DeleteWO_Worker(WO_Worker instance);
    partial void InsertIE_InvoicesItem(IE_InvoicesItem instance);
    partial void UpdateIE_InvoicesItem(IE_InvoicesItem instance);
    partial void DeleteIE_InvoicesItem(IE_InvoicesItem instance);
    partial void InsertIN_Invoice(IN_Invoice instance);
    partial void UpdateIN_Invoice(IN_Invoice instance);
    partial void DeleteIN_Invoice(IN_Invoice instance);
    partial void InsertOE_OrderItem(OE_OrderItem instance);
    partial void UpdateOE_OrderItem(OE_OrderItem instance);
    partial void DeleteOE_OrderItem(OE_OrderItem instance);
    partial void InsertOR_Order(OR_Order instance);
    partial void UpdateOR_Order(OR_Order instance);
    partial void DeleteOR_Order(OR_Order instance);
    partial void InsertPC_ProductCategory(PC_ProductCategory instance);
    partial void UpdatePC_ProductCategory(PC_ProductCategory instance);
    partial void DeletePC_ProductCategory(PC_ProductCategory instance);
    partial void InsertPO_Position(PO_Position instance);
    partial void UpdatePO_Position(PO_Position instance);
    partial void DeletePO_Position(PO_Position instance);
    partial void InsertPR_Product(PR_Product instance);
    partial void UpdatePR_Product(PR_Product instance);
    partial void DeletePR_Product(PR_Product instance);
    partial void InsertQT_QuantityType(QT_QuantityType instance);
    partial void UpdateQT_QuantityType(QT_QuantityType instance);
    partial void DeleteQT_QuantityType(QT_QuantityType instance);
    partial void InsertSP_Spedition(SP_Spedition instance);
    partial void UpdateSP_Spedition(SP_Spedition instance);
    partial void DeleteSP_Spedition(SP_Spedition instance);
    partial void InsertSU_Supplier(SU_Supplier instance);
    partial void UpdateSU_Supplier(SU_Supplier instance);
    partial void DeleteSU_Supplier(SU_Supplier instance);
    partial void InsertUS_User(US_User instance);
    partial void UpdateUS_User(US_User instance);
    partial void DeleteUS_User(US_User instance);
    #endregion
		
		public LinqDataLayerDataContext() : 
				base(global::WarehouseElectric.Properties.Settings.Default.ElectricWarehouseConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataLayerDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataLayerDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataLayerDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataLayerDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CU_Customer> CU_Customers
		{
			get
			{
				return this.GetTable<CU_Customer>();
			}
		}
		
		public System.Data.Linq.Table<WO_Worker> WO_Workers
		{
			get
			{
				return this.GetTable<WO_Worker>();
			}
		}
		
		public System.Data.Linq.Table<IE_InvoicesItem> IE_InvoicesItems
		{
			get
			{
				return this.GetTable<IE_InvoicesItem>();
			}
		}
		
		public System.Data.Linq.Table<IN_Invoice> IN_Invoices
		{
			get
			{
				return this.GetTable<IN_Invoice>();
			}
		}
		
		public System.Data.Linq.Table<OE_OrderItem> OE_OrderItems
		{
			get
			{
				return this.GetTable<OE_OrderItem>();
			}
		}
		
		public System.Data.Linq.Table<OR_Order> OR_Orders
		{
			get
			{
				return this.GetTable<OR_Order>();
			}
		}
		
		public System.Data.Linq.Table<PC_ProductCategory> PC_ProductCategories
		{
			get
			{
				return this.GetTable<PC_ProductCategory>();
			}
		}
		
		public System.Data.Linq.Table<PO_Position> PO_Positions
		{
			get
			{
				return this.GetTable<PO_Position>();
			}
		}
		
		public System.Data.Linq.Table<PR_Product> PR_Products
		{
			get
			{
				return this.GetTable<PR_Product>();
			}
		}
		
		public System.Data.Linq.Table<QT_QuantityType> QT_QuantityTypes
		{
			get
			{
				return this.GetTable<QT_QuantityType>();
			}
		}
		
		public System.Data.Linq.Table<SP_Spedition> SP_Speditions
		{
			get
			{
				return this.GetTable<SP_Spedition>();
			}
		}
		
		public System.Data.Linq.Table<SU_Supplier> SU_Suppliers
		{
			get
			{
				return this.GetTable<SU_Supplier>();
			}
		}
		
		public System.Data.Linq.Table<US_User> US_Users
		{
			get
			{
				return this.GetTable<US_User>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CU_Customers")]
	public partial class CU_Customer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CU_ID;
		
		private string _CU_NAME;
		
		private string _CU_STREET;
		
		private string _CU_POST_CODE;
		
		private string _CU_TOWN;
		
		private string _CU_PHONE;
		
		private System.Nullable<System.DateTime> _CU_ADDED;
		
		private System.Nullable<System.DateTime> _CU_LAST_MODIFIED;
		
		private EntitySet<IN_Invoice> _IN_Invoices;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCU_IDChanging(int value);
    partial void OnCU_IDChanged();
    partial void OnCU_NAMEChanging(string value);
    partial void OnCU_NAMEChanged();
    partial void OnCU_STREETChanging(string value);
    partial void OnCU_STREETChanged();
    partial void OnCU_POST_CODEChanging(string value);
    partial void OnCU_POST_CODEChanged();
    partial void OnCU_TOWNChanging(string value);
    partial void OnCU_TOWNChanged();
    partial void OnCU_PHONEChanging(string value);
    partial void OnCU_PHONEChanged();
    partial void OnCU_ADDEDChanging(System.Nullable<System.DateTime> value);
    partial void OnCU_ADDEDChanged();
    partial void OnCU_LAST_MODIFIEDChanging(System.Nullable<System.DateTime> value);
    partial void OnCU_LAST_MODIFIEDChanged();
    #endregion
		
		public CU_Customer()
		{
			this._IN_Invoices = new EntitySet<IN_Invoice>(new Action<IN_Invoice>(this.attach_IN_Invoices), new Action<IN_Invoice>(this.detach_IN_Invoices));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CU_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CU_ID
		{
			get
			{
				return this._CU_ID;
			}
			set
			{
				if ((this._CU_ID != value))
				{
					this.OnCU_IDChanging(value);
					this.SendPropertyChanging();
					this._CU_ID = value;
					this.SendPropertyChanged("CU_ID");
					this.OnCU_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CU_NAME", DbType="NVarChar(50)")]
		public string CU_NAME
		{
			get
			{
				return this._CU_NAME;
			}
			set
			{
				if ((this._CU_NAME != value))
				{
					this.OnCU_NAMEChanging(value);
					this.SendPropertyChanging();
					this._CU_NAME = value;
					this.SendPropertyChanged("CU_NAME");
					this.OnCU_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CU_STREET", DbType="NVarChar(100)")]
		public string CU_STREET
		{
			get
			{
				return this._CU_STREET;
			}
			set
			{
				if ((this._CU_STREET != value))
				{
					this.OnCU_STREETChanging(value);
					this.SendPropertyChanging();
					this._CU_STREET = value;
					this.SendPropertyChanged("CU_STREET");
					this.OnCU_STREETChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CU_POST_CODE", DbType="NVarChar(10)")]
		public string CU_POST_CODE
		{
			get
			{
				return this._CU_POST_CODE;
			}
			set
			{
				if ((this._CU_POST_CODE != value))
				{
					this.OnCU_POST_CODEChanging(value);
					this.SendPropertyChanging();
					this._CU_POST_CODE = value;
					this.SendPropertyChanged("CU_POST_CODE");
					this.OnCU_POST_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CU_TOWN", DbType="NVarChar(50)")]
		public string CU_TOWN
		{
			get
			{
				return this._CU_TOWN;
			}
			set
			{
				if ((this._CU_TOWN != value))
				{
					this.OnCU_TOWNChanging(value);
					this.SendPropertyChanging();
					this._CU_TOWN = value;
					this.SendPropertyChanged("CU_TOWN");
					this.OnCU_TOWNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CU_PHONE", DbType="NVarChar(15)")]
		public string CU_PHONE
		{
			get
			{
				return this._CU_PHONE;
			}
			set
			{
				if ((this._CU_PHONE != value))
				{
					this.OnCU_PHONEChanging(value);
					this.SendPropertyChanging();
					this._CU_PHONE = value;
					this.SendPropertyChanged("CU_PHONE");
					this.OnCU_PHONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CU_ADDED", DbType="DateTime")]
		public System.Nullable<System.DateTime> CU_ADDED
		{
			get
			{
				return this._CU_ADDED;
			}
			set
			{
				if ((this._CU_ADDED != value))
				{
					this.OnCU_ADDEDChanging(value);
					this.SendPropertyChanging();
					this._CU_ADDED = value;
					this.SendPropertyChanged("CU_ADDED");
					this.OnCU_ADDEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CU_LAST_MODIFIED", DbType="DateTime")]
		public System.Nullable<System.DateTime> CU_LAST_MODIFIED
		{
			get
			{
				return this._CU_LAST_MODIFIED;
			}
			set
			{
				if ((this._CU_LAST_MODIFIED != value))
				{
					this.OnCU_LAST_MODIFIEDChanging(value);
					this.SendPropertyChanging();
					this._CU_LAST_MODIFIED = value;
					this.SendPropertyChanged("CU_LAST_MODIFIED");
					this.OnCU_LAST_MODIFIEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CU_Customer_IN_Invoice", Storage="_IN_Invoices", ThisKey="CU_ID", OtherKey="IN_CU_ID")]
		public EntitySet<IN_Invoice> IN_Invoices
		{
			get
			{
				return this._IN_Invoices;
			}
			set
			{
				this._IN_Invoices.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_IN_Invoices(IN_Invoice entity)
		{
			this.SendPropertyChanging();
			entity.CU_Customer = this;
		}
		
		private void detach_IN_Invoices(IN_Invoice entity)
		{
			this.SendPropertyChanging();
			entity.CU_Customer = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WO_Workers")]
	public partial class WO_Worker : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _WO_ID;
		
		private int _WO_PO_ID;
		
		private string _WO_NAME;
		
		private string _WO_SURNAME;
		
		private string _WO_PHONE;
		
		private System.Nullable<System.DateTime> _WO_BIRTH_DATE;
		
		private System.Nullable<System.DateTime> _WO_WORKING_SINCE;
		
		private string _WO_PESEL;
		
		private System.Nullable<System.DateTime> _WO_ADDED;
		
		private System.Nullable<System.DateTime> _WO_LAST_MODIFIED;
		
		private EntitySet<IN_Invoice> _IN_Invoices;
		
		private EntitySet<OR_Order> _OR_Orders;
		
		private EntitySet<US_User> _US_Users;
		
		private EntityRef<PO_Position> _PO_Position;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWO_IDChanging(int value);
    partial void OnWO_IDChanged();
    partial void OnWO_PO_IDChanging(int value);
    partial void OnWO_PO_IDChanged();
    partial void OnWO_NAMEChanging(string value);
    partial void OnWO_NAMEChanged();
    partial void OnWO_SURNAMEChanging(string value);
    partial void OnWO_SURNAMEChanged();
    partial void OnWO_PHONEChanging(string value);
    partial void OnWO_PHONEChanged();
    partial void OnWO_BIRTH_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnWO_BIRTH_DATEChanged();
    partial void OnWO_WORKING_SINCEChanging(System.Nullable<System.DateTime> value);
    partial void OnWO_WORKING_SINCEChanged();
    partial void OnWO_PESELChanging(string value);
    partial void OnWO_PESELChanged();
    partial void OnWO_ADDEDChanging(System.Nullable<System.DateTime> value);
    partial void OnWO_ADDEDChanged();
    partial void OnWO_LAST_MODIFIEDChanging(System.Nullable<System.DateTime> value);
    partial void OnWO_LAST_MODIFIEDChanged();
    #endregion
		
		public WO_Worker()
		{
			this._IN_Invoices = new EntitySet<IN_Invoice>(new Action<IN_Invoice>(this.attach_IN_Invoices), new Action<IN_Invoice>(this.detach_IN_Invoices));
			this._OR_Orders = new EntitySet<OR_Order>(new Action<OR_Order>(this.attach_OR_Orders), new Action<OR_Order>(this.detach_OR_Orders));
			this._US_Users = new EntitySet<US_User>(new Action<US_User>(this.attach_US_Users), new Action<US_User>(this.detach_US_Users));
			this._PO_Position = default(EntityRef<PO_Position>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WO_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int WO_ID
		{
			get
			{
				return this._WO_ID;
			}
			set
			{
				if ((this._WO_ID != value))
				{
					this.OnWO_IDChanging(value);
					this.SendPropertyChanging();
					this._WO_ID = value;
					this.SendPropertyChanged("WO_ID");
					this.OnWO_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WO_PO_ID", DbType="Int NOT NULL")]
		public int WO_PO_ID
		{
			get
			{
				return this._WO_PO_ID;
			}
			set
			{
				if ((this._WO_PO_ID != value))
				{
					if (this._PO_Position.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnWO_PO_IDChanging(value);
					this.SendPropertyChanging();
					this._WO_PO_ID = value;
					this.SendPropertyChanged("WO_PO_ID");
					this.OnWO_PO_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WO_NAME", DbType="NVarChar(50)")]
		public string WO_NAME
		{
			get
			{
				return this._WO_NAME;
			}
			set
			{
				if ((this._WO_NAME != value))
				{
					this.OnWO_NAMEChanging(value);
					this.SendPropertyChanging();
					this._WO_NAME = value;
					this.SendPropertyChanged("WO_NAME");
					this.OnWO_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WO_SURNAME", DbType="NVarChar(50)")]
		public string WO_SURNAME
		{
			get
			{
				return this._WO_SURNAME;
			}
			set
			{
				if ((this._WO_SURNAME != value))
				{
					this.OnWO_SURNAMEChanging(value);
					this.SendPropertyChanging();
					this._WO_SURNAME = value;
					this.SendPropertyChanged("WO_SURNAME");
					this.OnWO_SURNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WO_PHONE", DbType="NVarChar(15)")]
		public string WO_PHONE
		{
			get
			{
				return this._WO_PHONE;
			}
			set
			{
				if ((this._WO_PHONE != value))
				{
					this.OnWO_PHONEChanging(value);
					this.SendPropertyChanging();
					this._WO_PHONE = value;
					this.SendPropertyChanged("WO_PHONE");
					this.OnWO_PHONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WO_BIRTH_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> WO_BIRTH_DATE
		{
			get
			{
				return this._WO_BIRTH_DATE;
			}
			set
			{
				if ((this._WO_BIRTH_DATE != value))
				{
					this.OnWO_BIRTH_DATEChanging(value);
					this.SendPropertyChanging();
					this._WO_BIRTH_DATE = value;
					this.SendPropertyChanged("WO_BIRTH_DATE");
					this.OnWO_BIRTH_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WO_WORKING_SINCE", DbType="DateTime")]
		public System.Nullable<System.DateTime> WO_WORKING_SINCE
		{
			get
			{
				return this._WO_WORKING_SINCE;
			}
			set
			{
				if ((this._WO_WORKING_SINCE != value))
				{
					this.OnWO_WORKING_SINCEChanging(value);
					this.SendPropertyChanging();
					this._WO_WORKING_SINCE = value;
					this.SendPropertyChanged("WO_WORKING_SINCE");
					this.OnWO_WORKING_SINCEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WO_PESEL", DbType="NVarChar(11)")]
		public string WO_PESEL
		{
			get
			{
				return this._WO_PESEL;
			}
			set
			{
				if ((this._WO_PESEL != value))
				{
					this.OnWO_PESELChanging(value);
					this.SendPropertyChanging();
					this._WO_PESEL = value;
					this.SendPropertyChanged("WO_PESEL");
					this.OnWO_PESELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WO_ADDED", DbType="DateTime")]
		public System.Nullable<System.DateTime> WO_ADDED
		{
			get
			{
				return this._WO_ADDED;
			}
			set
			{
				if ((this._WO_ADDED != value))
				{
					this.OnWO_ADDEDChanging(value);
					this.SendPropertyChanging();
					this._WO_ADDED = value;
					this.SendPropertyChanged("WO_ADDED");
					this.OnWO_ADDEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WO_LAST_MODIFIED", DbType="DateTime")]
		public System.Nullable<System.DateTime> WO_LAST_MODIFIED
		{
			get
			{
				return this._WO_LAST_MODIFIED;
			}
			set
			{
				if ((this._WO_LAST_MODIFIED != value))
				{
					this.OnWO_LAST_MODIFIEDChanging(value);
					this.SendPropertyChanging();
					this._WO_LAST_MODIFIED = value;
					this.SendPropertyChanged("WO_LAST_MODIFIED");
					this.OnWO_LAST_MODIFIEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WO_Worker_IN_Invoice", Storage="_IN_Invoices", ThisKey="WO_ID", OtherKey="IN_WO_ID")]
		public EntitySet<IN_Invoice> IN_Invoices
		{
			get
			{
				return this._IN_Invoices;
			}
			set
			{
				this._IN_Invoices.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WO_Worker_OR_Order", Storage="_OR_Orders", ThisKey="WO_ID", OtherKey="OR_WO_ID")]
		public EntitySet<OR_Order> OR_Orders
		{
			get
			{
				return this._OR_Orders;
			}
			set
			{
				this._OR_Orders.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WO_Worker_US_User", Storage="_US_Users", ThisKey="WO_ID", OtherKey="US_WO_ID")]
		public EntitySet<US_User> US_Users
		{
			get
			{
				return this._US_Users;
			}
			set
			{
				this._US_Users.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PO_Position_WO_Worker", Storage="_PO_Position", ThisKey="WO_PO_ID", OtherKey="PO_ID", IsForeignKey=true)]
		public PO_Position PO_Position
		{
			get
			{
				return this._PO_Position.Entity;
			}
			set
			{
				PO_Position previousValue = this._PO_Position.Entity;
				if (((previousValue != value) 
							|| (this._PO_Position.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PO_Position.Entity = null;
						previousValue.WO_Workers.Remove(this);
					}
					this._PO_Position.Entity = value;
					if ((value != null))
					{
						value.WO_Workers.Add(this);
						this._WO_PO_ID = value.PO_ID;
					}
					else
					{
						this._WO_PO_ID = default(int);
					}
					this.SendPropertyChanged("PO_Position");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_IN_Invoices(IN_Invoice entity)
		{
			this.SendPropertyChanging();
			entity.WO_Worker = this;
		}
		
		private void detach_IN_Invoices(IN_Invoice entity)
		{
			this.SendPropertyChanging();
			entity.WO_Worker = null;
		}
		
		private void attach_OR_Orders(OR_Order entity)
		{
			this.SendPropertyChanging();
			entity.WO_Worker = this;
		}
		
		private void detach_OR_Orders(OR_Order entity)
		{
			this.SendPropertyChanging();
			entity.WO_Worker = null;
		}
		
		private void attach_US_Users(US_User entity)
		{
			this.SendPropertyChanging();
			entity.WO_Worker = this;
		}
		
		private void detach_US_Users(US_User entity)
		{
			this.SendPropertyChanging();
			entity.WO_Worker = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IE_InvoicesItems")]
	public partial class IE_InvoicesItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IE_ID;
		
		private int _IE_IN_ID;
		
		private int _IE_PR_ID;
		
		private System.Nullable<decimal> _IE_QUANTITY;
		
		private System.Nullable<System.DateTime> _IE_ADDED;
		
		private System.Nullable<System.DateTime> _IE_LAST_MODIFIED;
		
		private System.Nullable<decimal> _IE_UNIT_PRICE;
		
		private System.Nullable<decimal> _IE_TOTAL_NETTO;
		
		private System.Nullable<decimal> _IE_TOTAL_VAT;
		
		private System.Nullable<decimal> _IE_TOTAL_BRUTTO;
		
		private System.Nullable<decimal> _IE_VAT_RATE;
		
		private EntityRef<IN_Invoice> _IN_Invoice;
		
		private EntityRef<PR_Product> _PR_Product;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIE_IDChanging(int value);
    partial void OnIE_IDChanged();
    partial void OnIE_IN_IDChanging(int value);
    partial void OnIE_IN_IDChanged();
    partial void OnIE_PR_IDChanging(int value);
    partial void OnIE_PR_IDChanged();
    partial void OnIE_QUANTITYChanging(System.Nullable<decimal> value);
    partial void OnIE_QUANTITYChanged();
    partial void OnIE_ADDEDChanging(System.Nullable<System.DateTime> value);
    partial void OnIE_ADDEDChanged();
    partial void OnIE_LAST_MODIFIEDChanging(System.Nullable<System.DateTime> value);
    partial void OnIE_LAST_MODIFIEDChanged();
    partial void OnIE_UNIT_PRICEChanging(System.Nullable<decimal> value);
    partial void OnIE_UNIT_PRICEChanged();
    partial void OnIE_TOTAL_NETTOChanging(System.Nullable<decimal> value);
    partial void OnIE_TOTAL_NETTOChanged();
    partial void OnIE_TOTAL_VATChanging(System.Nullable<decimal> value);
    partial void OnIE_TOTAL_VATChanged();
    partial void OnIE_TOTAL_BRUTTOChanging(System.Nullable<decimal> value);
    partial void OnIE_TOTAL_BRUTTOChanged();
    partial void OnIE_VAT_RATEChanging(System.Nullable<decimal> value);
    partial void OnIE_VAT_RATEChanged();
    #endregion
		
		public IE_InvoicesItem()
		{
			this._IN_Invoice = default(EntityRef<IN_Invoice>);
			this._PR_Product = default(EntityRef<PR_Product>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IE_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IE_ID
		{
			get
			{
				return this._IE_ID;
			}
			set
			{
				if ((this._IE_ID != value))
				{
					this.OnIE_IDChanging(value);
					this.SendPropertyChanging();
					this._IE_ID = value;
					this.SendPropertyChanged("IE_ID");
					this.OnIE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IE_IN_ID", DbType="Int NOT NULL")]
		public int IE_IN_ID
		{
			get
			{
				return this._IE_IN_ID;
			}
			set
			{
				if ((this._IE_IN_ID != value))
				{
					if (this._IN_Invoice.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIE_IN_IDChanging(value);
					this.SendPropertyChanging();
					this._IE_IN_ID = value;
					this.SendPropertyChanged("IE_IN_ID");
					this.OnIE_IN_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IE_PR_ID", DbType="Int NOT NULL")]
		public int IE_PR_ID
		{
			get
			{
				return this._IE_PR_ID;
			}
			set
			{
				if ((this._IE_PR_ID != value))
				{
					if (this._PR_Product.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIE_PR_IDChanging(value);
					this.SendPropertyChanging();
					this._IE_PR_ID = value;
					this.SendPropertyChanged("IE_PR_ID");
					this.OnIE_PR_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IE_QUANTITY", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> IE_QUANTITY
		{
			get
			{
				return this._IE_QUANTITY;
			}
			set
			{
				if ((this._IE_QUANTITY != value))
				{
					this.OnIE_QUANTITYChanging(value);
					this.SendPropertyChanging();
					this._IE_QUANTITY = value;
					this.SendPropertyChanged("IE_QUANTITY");
					this.OnIE_QUANTITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IE_ADDED", DbType="DateTime")]
		public System.Nullable<System.DateTime> IE_ADDED
		{
			get
			{
				return this._IE_ADDED;
			}
			set
			{
				if ((this._IE_ADDED != value))
				{
					this.OnIE_ADDEDChanging(value);
					this.SendPropertyChanging();
					this._IE_ADDED = value;
					this.SendPropertyChanged("IE_ADDED");
					this.OnIE_ADDEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IE_LAST_MODIFIED", DbType="DateTime")]
		public System.Nullable<System.DateTime> IE_LAST_MODIFIED
		{
			get
			{
				return this._IE_LAST_MODIFIED;
			}
			set
			{
				if ((this._IE_LAST_MODIFIED != value))
				{
					this.OnIE_LAST_MODIFIEDChanging(value);
					this.SendPropertyChanging();
					this._IE_LAST_MODIFIED = value;
					this.SendPropertyChanged("IE_LAST_MODIFIED");
					this.OnIE_LAST_MODIFIEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IE_UNIT_PRICE", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> IE_UNIT_PRICE
		{
			get
			{
				return this._IE_UNIT_PRICE;
			}
			set
			{
				if ((this._IE_UNIT_PRICE != value))
				{
					this.OnIE_UNIT_PRICEChanging(value);
					this.SendPropertyChanging();
					this._IE_UNIT_PRICE = value;
					this.SendPropertyChanged("IE_UNIT_PRICE");
					this.OnIE_UNIT_PRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IE_TOTAL_NETTO", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> IE_TOTAL_NETTO
		{
			get
			{
				return this._IE_TOTAL_NETTO;
			}
			set
			{
				if ((this._IE_TOTAL_NETTO != value))
				{
					this.OnIE_TOTAL_NETTOChanging(value);
					this.SendPropertyChanging();
					this._IE_TOTAL_NETTO = value;
					this.SendPropertyChanged("IE_TOTAL_NETTO");
					this.OnIE_TOTAL_NETTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IE_TOTAL_VAT", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> IE_TOTAL_VAT
		{
			get
			{
				return this._IE_TOTAL_VAT;
			}
			set
			{
				if ((this._IE_TOTAL_VAT != value))
				{
					this.OnIE_TOTAL_VATChanging(value);
					this.SendPropertyChanging();
					this._IE_TOTAL_VAT = value;
					this.SendPropertyChanged("IE_TOTAL_VAT");
					this.OnIE_TOTAL_VATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IE_TOTAL_BRUTTO", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> IE_TOTAL_BRUTTO
		{
			get
			{
				return this._IE_TOTAL_BRUTTO;
			}
			set
			{
				if ((this._IE_TOTAL_BRUTTO != value))
				{
					this.OnIE_TOTAL_BRUTTOChanging(value);
					this.SendPropertyChanging();
					this._IE_TOTAL_BRUTTO = value;
					this.SendPropertyChanged("IE_TOTAL_BRUTTO");
					this.OnIE_TOTAL_BRUTTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IE_VAT_RATE", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> IE_VAT_RATE
		{
			get
			{
				return this._IE_VAT_RATE;
			}
			set
			{
				if ((this._IE_VAT_RATE != value))
				{
					this.OnIE_VAT_RATEChanging(value);
					this.SendPropertyChanging();
					this._IE_VAT_RATE = value;
					this.SendPropertyChanged("IE_VAT_RATE");
					this.OnIE_VAT_RATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="IN_Invoice_IE_InvoicesItem", Storage="_IN_Invoice", ThisKey="IE_IN_ID", OtherKey="IN_ID", IsForeignKey=true)]
		public IN_Invoice IN_Invoice
		{
			get
			{
				return this._IN_Invoice.Entity;
			}
			set
			{
				IN_Invoice previousValue = this._IN_Invoice.Entity;
				if (((previousValue != value) 
							|| (this._IN_Invoice.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._IN_Invoice.Entity = null;
						previousValue.IE_InvoicesItems.Remove(this);
					}
					this._IN_Invoice.Entity = value;
					if ((value != null))
					{
						value.IE_InvoicesItems.Add(this);
						this._IE_IN_ID = value.IN_ID;
					}
					else
					{
						this._IE_IN_ID = default(int);
					}
					this.SendPropertyChanged("IN_Invoice");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PR_Product_IE_InvoicesItem", Storage="_PR_Product", ThisKey="IE_PR_ID", OtherKey="PR_ID", IsForeignKey=true)]
		public PR_Product PR_Product
		{
			get
			{
				return this._PR_Product.Entity;
			}
			set
			{
				PR_Product previousValue = this._PR_Product.Entity;
				if (((previousValue != value) 
							|| (this._PR_Product.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PR_Product.Entity = null;
						previousValue.IE_InvoicesItems.Remove(this);
					}
					this._PR_Product.Entity = value;
					if ((value != null))
					{
						value.IE_InvoicesItems.Add(this);
						this._IE_PR_ID = value.PR_ID;
					}
					else
					{
						this._IE_PR_ID = default(int);
					}
					this.SendPropertyChanged("PR_Product");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IN_Invoices")]
	public partial class IN_Invoice : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IN_ID;
		
		private int _IN_CU_ID;
		
		private int _IN_WO_ID;
		
		private int _IN_SP_ID;
		
		private System.Nullable<System.DateTime> _IN_ADDED;
		
		private System.Nullable<System.DateTime> _IN_LAST_MODIFIED;
		
		private System.Nullable<decimal> _IN_TOTAL;
		
		private System.Nullable<decimal> _IN_SPEDITION_COST;
		
		private EntitySet<IE_InvoicesItem> _IE_InvoicesItems;
		
		private EntityRef<CU_Customer> _CU_Customer;
		
		private EntityRef<WO_Worker> _WO_Worker;
		
		private EntityRef<SP_Spedition> _SP_Spedition;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIN_IDChanging(int value);
    partial void OnIN_IDChanged();
    partial void OnIN_CU_IDChanging(int value);
    partial void OnIN_CU_IDChanged();
    partial void OnIN_WO_IDChanging(int value);
    partial void OnIN_WO_IDChanged();
    partial void OnIN_SP_IDChanging(int value);
    partial void OnIN_SP_IDChanged();
    partial void OnIN_ADDEDChanging(System.Nullable<System.DateTime> value);
    partial void OnIN_ADDEDChanged();
    partial void OnIN_LAST_MODIFIEDChanging(System.Nullable<System.DateTime> value);
    partial void OnIN_LAST_MODIFIEDChanged();
    partial void OnIN_TOTALChanging(System.Nullable<decimal> value);
    partial void OnIN_TOTALChanged();
    partial void OnIN_SPEDITION_COSTChanging(System.Nullable<decimal> value);
    partial void OnIN_SPEDITION_COSTChanged();
    #endregion
		
		public IN_Invoice()
		{
			this._IE_InvoicesItems = new EntitySet<IE_InvoicesItem>(new Action<IE_InvoicesItem>(this.attach_IE_InvoicesItems), new Action<IE_InvoicesItem>(this.detach_IE_InvoicesItems));
			this._CU_Customer = default(EntityRef<CU_Customer>);
			this._WO_Worker = default(EntityRef<WO_Worker>);
			this._SP_Spedition = default(EntityRef<SP_Spedition>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IN_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IN_ID
		{
			get
			{
				return this._IN_ID;
			}
			set
			{
				if ((this._IN_ID != value))
				{
					this.OnIN_IDChanging(value);
					this.SendPropertyChanging();
					this._IN_ID = value;
					this.SendPropertyChanged("IN_ID");
					this.OnIN_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IN_CU_ID", DbType="Int NOT NULL")]
		public int IN_CU_ID
		{
			get
			{
				return this._IN_CU_ID;
			}
			set
			{
				if ((this._IN_CU_ID != value))
				{
					if (this._CU_Customer.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIN_CU_IDChanging(value);
					this.SendPropertyChanging();
					this._IN_CU_ID = value;
					this.SendPropertyChanged("IN_CU_ID");
					this.OnIN_CU_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IN_WO_ID", DbType="Int NOT NULL")]
		public int IN_WO_ID
		{
			get
			{
				return this._IN_WO_ID;
			}
			set
			{
				if ((this._IN_WO_ID != value))
				{
					if (this._WO_Worker.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIN_WO_IDChanging(value);
					this.SendPropertyChanging();
					this._IN_WO_ID = value;
					this.SendPropertyChanged("IN_WO_ID");
					this.OnIN_WO_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IN_SP_ID", DbType="Int NOT NULL")]
		public int IN_SP_ID
		{
			get
			{
				return this._IN_SP_ID;
			}
			set
			{
				if ((this._IN_SP_ID != value))
				{
					if (this._SP_Spedition.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIN_SP_IDChanging(value);
					this.SendPropertyChanging();
					this._IN_SP_ID = value;
					this.SendPropertyChanged("IN_SP_ID");
					this.OnIN_SP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IN_ADDED", DbType="DateTime")]
		public System.Nullable<System.DateTime> IN_ADDED
		{
			get
			{
				return this._IN_ADDED;
			}
			set
			{
				if ((this._IN_ADDED != value))
				{
					this.OnIN_ADDEDChanging(value);
					this.SendPropertyChanging();
					this._IN_ADDED = value;
					this.SendPropertyChanged("IN_ADDED");
					this.OnIN_ADDEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IN_LAST_MODIFIED", DbType="DateTime")]
		public System.Nullable<System.DateTime> IN_LAST_MODIFIED
		{
			get
			{
				return this._IN_LAST_MODIFIED;
			}
			set
			{
				if ((this._IN_LAST_MODIFIED != value))
				{
					this.OnIN_LAST_MODIFIEDChanging(value);
					this.SendPropertyChanging();
					this._IN_LAST_MODIFIED = value;
					this.SendPropertyChanged("IN_LAST_MODIFIED");
					this.OnIN_LAST_MODIFIEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IN_TOTAL", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> IN_TOTAL
		{
			get
			{
				return this._IN_TOTAL;
			}
			set
			{
				if ((this._IN_TOTAL != value))
				{
					this.OnIN_TOTALChanging(value);
					this.SendPropertyChanging();
					this._IN_TOTAL = value;
					this.SendPropertyChanged("IN_TOTAL");
					this.OnIN_TOTALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IN_SPEDITION_COST", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> IN_SPEDITION_COST
		{
			get
			{
				return this._IN_SPEDITION_COST;
			}
			set
			{
				if ((this._IN_SPEDITION_COST != value))
				{
					this.OnIN_SPEDITION_COSTChanging(value);
					this.SendPropertyChanging();
					this._IN_SPEDITION_COST = value;
					this.SendPropertyChanged("IN_SPEDITION_COST");
					this.OnIN_SPEDITION_COSTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="IN_Invoice_IE_InvoicesItem", Storage="_IE_InvoicesItems", ThisKey="IN_ID", OtherKey="IE_IN_ID")]
		public EntitySet<IE_InvoicesItem> IE_InvoicesItems
		{
			get
			{
				return this._IE_InvoicesItems;
			}
			set
			{
				this._IE_InvoicesItems.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CU_Customer_IN_Invoice", Storage="_CU_Customer", ThisKey="IN_CU_ID", OtherKey="CU_ID", IsForeignKey=true)]
		public CU_Customer CU_Customer
		{
			get
			{
				return this._CU_Customer.Entity;
			}
			set
			{
				CU_Customer previousValue = this._CU_Customer.Entity;
				if (((previousValue != value) 
							|| (this._CU_Customer.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CU_Customer.Entity = null;
						previousValue.IN_Invoices.Remove(this);
					}
					this._CU_Customer.Entity = value;
					if ((value != null))
					{
						value.IN_Invoices.Add(this);
						this._IN_CU_ID = value.CU_ID;
					}
					else
					{
						this._IN_CU_ID = default(int);
					}
					this.SendPropertyChanged("CU_Customer");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WO_Worker_IN_Invoice", Storage="_WO_Worker", ThisKey="IN_WO_ID", OtherKey="WO_ID", IsForeignKey=true)]
		public WO_Worker WO_Worker
		{
			get
			{
				return this._WO_Worker.Entity;
			}
			set
			{
				WO_Worker previousValue = this._WO_Worker.Entity;
				if (((previousValue != value) 
							|| (this._WO_Worker.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._WO_Worker.Entity = null;
						previousValue.IN_Invoices.Remove(this);
					}
					this._WO_Worker.Entity = value;
					if ((value != null))
					{
						value.IN_Invoices.Add(this);
						this._IN_WO_ID = value.WO_ID;
					}
					else
					{
						this._IN_WO_ID = default(int);
					}
					this.SendPropertyChanged("WO_Worker");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SP_Spedition_IN_Invoice", Storage="_SP_Spedition", ThisKey="IN_SP_ID", OtherKey="SP_ID", IsForeignKey=true)]
		public SP_Spedition SP_Spedition
		{
			get
			{
				return this._SP_Spedition.Entity;
			}
			set
			{
				SP_Spedition previousValue = this._SP_Spedition.Entity;
				if (((previousValue != value) 
							|| (this._SP_Spedition.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SP_Spedition.Entity = null;
						previousValue.IN_Invoices.Remove(this);
					}
					this._SP_Spedition.Entity = value;
					if ((value != null))
					{
						value.IN_Invoices.Add(this);
						this._IN_SP_ID = value.SP_ID;
					}
					else
					{
						this._IN_SP_ID = default(int);
					}
					this.SendPropertyChanged("SP_Spedition");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_IE_InvoicesItems(IE_InvoicesItem entity)
		{
			this.SendPropertyChanging();
			entity.IN_Invoice = this;
		}
		
		private void detach_IE_InvoicesItems(IE_InvoicesItem entity)
		{
			this.SendPropertyChanging();
			entity.IN_Invoice = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OE_OrderItems")]
	public partial class OE_OrderItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _OE_ID;
		
		private int _OE_PR_ID;
		
		private int _OE_OR_ID;
		
		private System.Nullable<decimal> _OE_QUANTITY;
		
		private System.Nullable<System.DateTime> _OE_ADDED;
		
		private System.Nullable<System.DateTime> _OE_LAST_MODIFIED;
		
		private System.Nullable<decimal> _OE_UNIT_PRICE;
		
		private System.Nullable<decimal> _OE_TOTAL_NETTO;
		
		private System.Nullable<decimal> _OE_TOTAL_VAT;
		
		private System.Nullable<decimal> _OE_TOTAL_BRUTTO;
		
		private System.Nullable<decimal> _OE_VAT_RATE;
		
		private EntityRef<OR_Order> _OR_Order;
		
		private EntityRef<PR_Product> _PR_Product;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOE_IDChanging(int value);
    partial void OnOE_IDChanged();
    partial void OnOE_PR_IDChanging(int value);
    partial void OnOE_PR_IDChanged();
    partial void OnOE_OR_IDChanging(int value);
    partial void OnOE_OR_IDChanged();
    partial void OnOE_QUANTITYChanging(System.Nullable<decimal> value);
    partial void OnOE_QUANTITYChanged();
    partial void OnOE_ADDEDChanging(System.Nullable<System.DateTime> value);
    partial void OnOE_ADDEDChanged();
    partial void OnOE_LAST_MODIFIEDChanging(System.Nullable<System.DateTime> value);
    partial void OnOE_LAST_MODIFIEDChanged();
    partial void OnOE_UNIT_PRICEChanging(System.Nullable<decimal> value);
    partial void OnOE_UNIT_PRICEChanged();
    partial void OnOE_TOTAL_NETTOChanging(System.Nullable<decimal> value);
    partial void OnOE_TOTAL_NETTOChanged();
    partial void OnOE_TOTAL_VATChanging(System.Nullable<decimal> value);
    partial void OnOE_TOTAL_VATChanged();
    partial void OnOE_TOTAL_BRUTTOChanging(System.Nullable<decimal> value);
    partial void OnOE_TOTAL_BRUTTOChanged();
    partial void OnOE_VAT_RATEChanging(System.Nullable<decimal> value);
    partial void OnOE_VAT_RATEChanged();
    #endregion
		
		public OE_OrderItem()
		{
			this._OR_Order = default(EntityRef<OR_Order>);
			this._PR_Product = default(EntityRef<PR_Product>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OE_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int OE_ID
		{
			get
			{
				return this._OE_ID;
			}
			set
			{
				if ((this._OE_ID != value))
				{
					this.OnOE_IDChanging(value);
					this.SendPropertyChanging();
					this._OE_ID = value;
					this.SendPropertyChanged("OE_ID");
					this.OnOE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OE_PR_ID", DbType="Int NOT NULL")]
		public int OE_PR_ID
		{
			get
			{
				return this._OE_PR_ID;
			}
			set
			{
				if ((this._OE_PR_ID != value))
				{
					if (this._PR_Product.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnOE_PR_IDChanging(value);
					this.SendPropertyChanging();
					this._OE_PR_ID = value;
					this.SendPropertyChanged("OE_PR_ID");
					this.OnOE_PR_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OE_OR_ID", DbType="Int NOT NULL")]
		public int OE_OR_ID
		{
			get
			{
				return this._OE_OR_ID;
			}
			set
			{
				if ((this._OE_OR_ID != value))
				{
					if (this._OR_Order.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnOE_OR_IDChanging(value);
					this.SendPropertyChanging();
					this._OE_OR_ID = value;
					this.SendPropertyChanged("OE_OR_ID");
					this.OnOE_OR_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OE_QUANTITY", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> OE_QUANTITY
		{
			get
			{
				return this._OE_QUANTITY;
			}
			set
			{
				if ((this._OE_QUANTITY != value))
				{
					this.OnOE_QUANTITYChanging(value);
					this.SendPropertyChanging();
					this._OE_QUANTITY = value;
					this.SendPropertyChanged("OE_QUANTITY");
					this.OnOE_QUANTITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OE_ADDED", DbType="DateTime")]
		public System.Nullable<System.DateTime> OE_ADDED
		{
			get
			{
				return this._OE_ADDED;
			}
			set
			{
				if ((this._OE_ADDED != value))
				{
					this.OnOE_ADDEDChanging(value);
					this.SendPropertyChanging();
					this._OE_ADDED = value;
					this.SendPropertyChanged("OE_ADDED");
					this.OnOE_ADDEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OE_LAST_MODIFIED", DbType="DateTime")]
		public System.Nullable<System.DateTime> OE_LAST_MODIFIED
		{
			get
			{
				return this._OE_LAST_MODIFIED;
			}
			set
			{
				if ((this._OE_LAST_MODIFIED != value))
				{
					this.OnOE_LAST_MODIFIEDChanging(value);
					this.SendPropertyChanging();
					this._OE_LAST_MODIFIED = value;
					this.SendPropertyChanged("OE_LAST_MODIFIED");
					this.OnOE_LAST_MODIFIEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OE_UNIT_PRICE", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> OE_UNIT_PRICE
		{
			get
			{
				return this._OE_UNIT_PRICE;
			}
			set
			{
				if ((this._OE_UNIT_PRICE != value))
				{
					this.OnOE_UNIT_PRICEChanging(value);
					this.SendPropertyChanging();
					this._OE_UNIT_PRICE = value;
					this.SendPropertyChanged("OE_UNIT_PRICE");
					this.OnOE_UNIT_PRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OE_TOTAL_NETTO", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> OE_TOTAL_NETTO
		{
			get
			{
				return this._OE_TOTAL_NETTO;
			}
			set
			{
				if ((this._OE_TOTAL_NETTO != value))
				{
					this.OnOE_TOTAL_NETTOChanging(value);
					this.SendPropertyChanging();
					this._OE_TOTAL_NETTO = value;
					this.SendPropertyChanged("OE_TOTAL_NETTO");
					this.OnOE_TOTAL_NETTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OE_TOTAL_VAT", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> OE_TOTAL_VAT
		{
			get
			{
				return this._OE_TOTAL_VAT;
			}
			set
			{
				if ((this._OE_TOTAL_VAT != value))
				{
					this.OnOE_TOTAL_VATChanging(value);
					this.SendPropertyChanging();
					this._OE_TOTAL_VAT = value;
					this.SendPropertyChanged("OE_TOTAL_VAT");
					this.OnOE_TOTAL_VATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OE_TOTAL_BRUTTO", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> OE_TOTAL_BRUTTO
		{
			get
			{
				return this._OE_TOTAL_BRUTTO;
			}
			set
			{
				if ((this._OE_TOTAL_BRUTTO != value))
				{
					this.OnOE_TOTAL_BRUTTOChanging(value);
					this.SendPropertyChanging();
					this._OE_TOTAL_BRUTTO = value;
					this.SendPropertyChanged("OE_TOTAL_BRUTTO");
					this.OnOE_TOTAL_BRUTTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OE_VAT_RATE", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> OE_VAT_RATE
		{
			get
			{
				return this._OE_VAT_RATE;
			}
			set
			{
				if ((this._OE_VAT_RATE != value))
				{
					this.OnOE_VAT_RATEChanging(value);
					this.SendPropertyChanging();
					this._OE_VAT_RATE = value;
					this.SendPropertyChanged("OE_VAT_RATE");
					this.OnOE_VAT_RATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="OR_Order_OE_OrderItem", Storage="_OR_Order", ThisKey="OE_OR_ID", OtherKey="OR_ID", IsForeignKey=true)]
		public OR_Order OR_Order
		{
			get
			{
				return this._OR_Order.Entity;
			}
			set
			{
				OR_Order previousValue = this._OR_Order.Entity;
				if (((previousValue != value) 
							|| (this._OR_Order.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._OR_Order.Entity = null;
						previousValue.OE_OrderItems.Remove(this);
					}
					this._OR_Order.Entity = value;
					if ((value != null))
					{
						value.OE_OrderItems.Add(this);
						this._OE_OR_ID = value.OR_ID;
					}
					else
					{
						this._OE_OR_ID = default(int);
					}
					this.SendPropertyChanged("OR_Order");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PR_Product_OE_OrderItem", Storage="_PR_Product", ThisKey="OE_PR_ID", OtherKey="PR_ID", IsForeignKey=true)]
		public PR_Product PR_Product
		{
			get
			{
				return this._PR_Product.Entity;
			}
			set
			{
				PR_Product previousValue = this._PR_Product.Entity;
				if (((previousValue != value) 
							|| (this._PR_Product.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PR_Product.Entity = null;
						previousValue.OE_OrderItems.Remove(this);
					}
					this._PR_Product.Entity = value;
					if ((value != null))
					{
						value.OE_OrderItems.Add(this);
						this._OE_PR_ID = value.PR_ID;
					}
					else
					{
						this._OE_PR_ID = default(int);
					}
					this.SendPropertyChanged("PR_Product");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OR_Orders")]
	public partial class OR_Order : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _OR_ID;
		
		private int _OR_SU_ID;
		
		private int _OR_WO_ID;
		
		private System.Nullable<System.DateTime> _OR_ADDED;
		
		private System.Nullable<System.DateTime> _OR_LAST_MODIFIED;
		
		private EntitySet<OE_OrderItem> _OE_OrderItems;
		
		private EntityRef<WO_Worker> _WO_Worker;
		
		private EntityRef<SU_Supplier> _SU_Supplier;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOR_IDChanging(int value);
    partial void OnOR_IDChanged();
    partial void OnOR_SU_IDChanging(int value);
    partial void OnOR_SU_IDChanged();
    partial void OnOR_WO_IDChanging(int value);
    partial void OnOR_WO_IDChanged();
    partial void OnOR_ADDEDChanging(System.Nullable<System.DateTime> value);
    partial void OnOR_ADDEDChanged();
    partial void OnOR_LAST_MODIFIEDChanging(System.Nullable<System.DateTime> value);
    partial void OnOR_LAST_MODIFIEDChanged();
    #endregion
		
		public OR_Order()
		{
			this._OE_OrderItems = new EntitySet<OE_OrderItem>(new Action<OE_OrderItem>(this.attach_OE_OrderItems), new Action<OE_OrderItem>(this.detach_OE_OrderItems));
			this._WO_Worker = default(EntityRef<WO_Worker>);
			this._SU_Supplier = default(EntityRef<SU_Supplier>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OR_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int OR_ID
		{
			get
			{
				return this._OR_ID;
			}
			set
			{
				if ((this._OR_ID != value))
				{
					this.OnOR_IDChanging(value);
					this.SendPropertyChanging();
					this._OR_ID = value;
					this.SendPropertyChanged("OR_ID");
					this.OnOR_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OR_SU_ID", DbType="Int NOT NULL")]
		public int OR_SU_ID
		{
			get
			{
				return this._OR_SU_ID;
			}
			set
			{
				if ((this._OR_SU_ID != value))
				{
					if (this._SU_Supplier.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnOR_SU_IDChanging(value);
					this.SendPropertyChanging();
					this._OR_SU_ID = value;
					this.SendPropertyChanged("OR_SU_ID");
					this.OnOR_SU_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OR_WO_ID", DbType="Int NOT NULL")]
		public int OR_WO_ID
		{
			get
			{
				return this._OR_WO_ID;
			}
			set
			{
				if ((this._OR_WO_ID != value))
				{
					if (this._WO_Worker.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnOR_WO_IDChanging(value);
					this.SendPropertyChanging();
					this._OR_WO_ID = value;
					this.SendPropertyChanged("OR_WO_ID");
					this.OnOR_WO_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OR_ADDED", DbType="DateTime")]
		public System.Nullable<System.DateTime> OR_ADDED
		{
			get
			{
				return this._OR_ADDED;
			}
			set
			{
				if ((this._OR_ADDED != value))
				{
					this.OnOR_ADDEDChanging(value);
					this.SendPropertyChanging();
					this._OR_ADDED = value;
					this.SendPropertyChanged("OR_ADDED");
					this.OnOR_ADDEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OR_LAST_MODIFIED", DbType="DateTime")]
		public System.Nullable<System.DateTime> OR_LAST_MODIFIED
		{
			get
			{
				return this._OR_LAST_MODIFIED;
			}
			set
			{
				if ((this._OR_LAST_MODIFIED != value))
				{
					this.OnOR_LAST_MODIFIEDChanging(value);
					this.SendPropertyChanging();
					this._OR_LAST_MODIFIED = value;
					this.SendPropertyChanged("OR_LAST_MODIFIED");
					this.OnOR_LAST_MODIFIEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="OR_Order_OE_OrderItem", Storage="_OE_OrderItems", ThisKey="OR_ID", OtherKey="OE_OR_ID")]
		public EntitySet<OE_OrderItem> OE_OrderItems
		{
			get
			{
				return this._OE_OrderItems;
			}
			set
			{
				this._OE_OrderItems.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WO_Worker_OR_Order", Storage="_WO_Worker", ThisKey="OR_WO_ID", OtherKey="WO_ID", IsForeignKey=true)]
		public WO_Worker WO_Worker
		{
			get
			{
				return this._WO_Worker.Entity;
			}
			set
			{
				WO_Worker previousValue = this._WO_Worker.Entity;
				if (((previousValue != value) 
							|| (this._WO_Worker.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._WO_Worker.Entity = null;
						previousValue.OR_Orders.Remove(this);
					}
					this._WO_Worker.Entity = value;
					if ((value != null))
					{
						value.OR_Orders.Add(this);
						this._OR_WO_ID = value.WO_ID;
					}
					else
					{
						this._OR_WO_ID = default(int);
					}
					this.SendPropertyChanged("WO_Worker");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SU_Supplier_OR_Order", Storage="_SU_Supplier", ThisKey="OR_SU_ID", OtherKey="SU_ID", IsForeignKey=true)]
		public SU_Supplier SU_Supplier
		{
			get
			{
				return this._SU_Supplier.Entity;
			}
			set
			{
				SU_Supplier previousValue = this._SU_Supplier.Entity;
				if (((previousValue != value) 
							|| (this._SU_Supplier.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SU_Supplier.Entity = null;
						previousValue.OR_Orders.Remove(this);
					}
					this._SU_Supplier.Entity = value;
					if ((value != null))
					{
						value.OR_Orders.Add(this);
						this._OR_SU_ID = value.SU_ID;
					}
					else
					{
						this._OR_SU_ID = default(int);
					}
					this.SendPropertyChanged("SU_Supplier");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_OE_OrderItems(OE_OrderItem entity)
		{
			this.SendPropertyChanging();
			entity.OR_Order = this;
		}
		
		private void detach_OE_OrderItems(OE_OrderItem entity)
		{
			this.SendPropertyChanging();
			entity.OR_Order = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PC_ProductCategories")]
	public partial class PC_ProductCategory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PC_ID;
		
		private System.Nullable<int> _PC_PC_ID;
		
		private string _PC_NAME;
		
		private EntitySet<PC_ProductCategory> _PC_ProductCategories;
		
		private EntitySet<PR_Product> _PR_Products;
		
		private EntityRef<PC_ProductCategory> _PC_ProductCategory1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPC_IDChanging(int value);
    partial void OnPC_IDChanged();
    partial void OnPC_PC_IDChanging(System.Nullable<int> value);
    partial void OnPC_PC_IDChanged();
    partial void OnPC_NAMEChanging(string value);
    partial void OnPC_NAMEChanged();
    #endregion
		
		public PC_ProductCategory()
		{
			this._PC_ProductCategories = new EntitySet<PC_ProductCategory>(new Action<PC_ProductCategory>(this.attach_PC_ProductCategories), new Action<PC_ProductCategory>(this.detach_PC_ProductCategories));
			this._PR_Products = new EntitySet<PR_Product>(new Action<PR_Product>(this.attach_PR_Products), new Action<PR_Product>(this.detach_PR_Products));
			this._PC_ProductCategory1 = default(EntityRef<PC_ProductCategory>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PC_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PC_ID
		{
			get
			{
				return this._PC_ID;
			}
			set
			{
				if ((this._PC_ID != value))
				{
					this.OnPC_IDChanging(value);
					this.SendPropertyChanging();
					this._PC_ID = value;
					this.SendPropertyChanged("PC_ID");
					this.OnPC_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PC_PC_ID", DbType="Int")]
		public System.Nullable<int> PC_PC_ID
		{
			get
			{
				return this._PC_PC_ID;
			}
			set
			{
				if ((this._PC_PC_ID != value))
				{
					if (this._PC_ProductCategory1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPC_PC_IDChanging(value);
					this.SendPropertyChanging();
					this._PC_PC_ID = value;
					this.SendPropertyChanged("PC_PC_ID");
					this.OnPC_PC_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PC_NAME", DbType="NVarChar(50)")]
		public string PC_NAME
		{
			get
			{
				return this._PC_NAME;
			}
			set
			{
				if ((this._PC_NAME != value))
				{
					this.OnPC_NAMEChanging(value);
					this.SendPropertyChanging();
					this._PC_NAME = value;
					this.SendPropertyChanged("PC_NAME");
					this.OnPC_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PC_ProductCategory_PC_ProductCategory", Storage="_PC_ProductCategories", ThisKey="PC_ID", OtherKey="PC_PC_ID")]
		public EntitySet<PC_ProductCategory> PC_ProductCategories
		{
			get
			{
				return this._PC_ProductCategories;
			}
			set
			{
				this._PC_ProductCategories.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PC_ProductCategory_PR_Product", Storage="_PR_Products", ThisKey="PC_ID", OtherKey="PR_PC_ID")]
		public EntitySet<PR_Product> PR_Products
		{
			get
			{
				return this._PR_Products;
			}
			set
			{
				this._PR_Products.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PC_ProductCategory_PC_ProductCategory", Storage="_PC_ProductCategory1", ThisKey="PC_PC_ID", OtherKey="PC_ID", IsForeignKey=true)]
		public PC_ProductCategory PC_ProductCategory1
		{
			get
			{
				return this._PC_ProductCategory1.Entity;
			}
			set
			{
				PC_ProductCategory previousValue = this._PC_ProductCategory1.Entity;
				if (((previousValue != value) 
							|| (this._PC_ProductCategory1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PC_ProductCategory1.Entity = null;
						previousValue.PC_ProductCategories.Remove(this);
					}
					this._PC_ProductCategory1.Entity = value;
					if ((value != null))
					{
						value.PC_ProductCategories.Add(this);
						this._PC_PC_ID = value.PC_ID;
					}
					else
					{
						this._PC_PC_ID = default(Nullable<int>);
					}
					this.SendPropertyChanged("PC_ProductCategory1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PC_ProductCategories(PC_ProductCategory entity)
		{
			this.SendPropertyChanging();
			entity.PC_ProductCategory1 = this;
		}
		
		private void detach_PC_ProductCategories(PC_ProductCategory entity)
		{
			this.SendPropertyChanging();
			entity.PC_ProductCategory1 = null;
		}
		
		private void attach_PR_Products(PR_Product entity)
		{
			this.SendPropertyChanging();
			entity.PC_ProductCategory = this;
		}
		
		private void detach_PR_Products(PR_Product entity)
		{
			this.SendPropertyChanging();
			entity.PC_ProductCategory = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PO_Positions")]
	public partial class PO_Position : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PO_ID;
		
		private string _PO_NAME;
		
		private EntitySet<WO_Worker> _WO_Workers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPO_IDChanging(int value);
    partial void OnPO_IDChanged();
    partial void OnPO_NAMEChanging(string value);
    partial void OnPO_NAMEChanged();
    #endregion
		
		public PO_Position()
		{
			this._WO_Workers = new EntitySet<WO_Worker>(new Action<WO_Worker>(this.attach_WO_Workers), new Action<WO_Worker>(this.detach_WO_Workers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PO_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PO_ID
		{
			get
			{
				return this._PO_ID;
			}
			set
			{
				if ((this._PO_ID != value))
				{
					this.OnPO_IDChanging(value);
					this.SendPropertyChanging();
					this._PO_ID = value;
					this.SendPropertyChanged("PO_ID");
					this.OnPO_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PO_NAME", DbType="NVarChar(50)")]
		public string PO_NAME
		{
			get
			{
				return this._PO_NAME;
			}
			set
			{
				if ((this._PO_NAME != value))
				{
					this.OnPO_NAMEChanging(value);
					this.SendPropertyChanging();
					this._PO_NAME = value;
					this.SendPropertyChanged("PO_NAME");
					this.OnPO_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PO_Position_WO_Worker", Storage="_WO_Workers", ThisKey="PO_ID", OtherKey="WO_PO_ID")]
		public EntitySet<WO_Worker> WO_Workers
		{
			get
			{
				return this._WO_Workers;
			}
			set
			{
				this._WO_Workers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_WO_Workers(WO_Worker entity)
		{
			this.SendPropertyChanging();
			entity.PO_Position = this;
		}
		
		private void detach_WO_Workers(WO_Worker entity)
		{
			this.SendPropertyChanging();
			entity.PO_Position = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PR_Products")]
	public partial class PR_Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PR_ID;
		
		private int _PR_PC_ID;
		
		private int _PR_QT_ID;
		
		private string _PR_NAME;
		
		private System.Nullable<decimal> _PR_DEPOT_QUANTITY;
		
		private System.Nullable<decimal> _PR_UNIT_PRICE;
		
		private System.Nullable<System.DateTime> _PR_ADDED;
		
		private System.Nullable<System.DateTime> _PR_LAST_MODIFIED;
		
		private System.Nullable<bool> _PR_IS_ACTIVE;
		
		private System.Nullable<bool> _PR_USED;
		
		private EntitySet<IE_InvoicesItem> _IE_InvoicesItems;
		
		private EntitySet<OE_OrderItem> _OE_OrderItems;
		
		private EntityRef<PC_ProductCategory> _PC_ProductCategory;
		
		private EntityRef<QT_QuantityType> _QT_QuantityType;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPR_IDChanging(int value);
    partial void OnPR_IDChanged();
    partial void OnPR_PC_IDChanging(int value);
    partial void OnPR_PC_IDChanged();
    partial void OnPR_QT_IDChanging(int value);
    partial void OnPR_QT_IDChanged();
    partial void OnPR_NAMEChanging(string value);
    partial void OnPR_NAMEChanged();
    partial void OnPR_DEPOT_QUANTITYChanging(System.Nullable<decimal> value);
    partial void OnPR_DEPOT_QUANTITYChanged();
    partial void OnPR_UNIT_PRICEChanging(System.Nullable<decimal> value);
    partial void OnPR_UNIT_PRICEChanged();
    partial void OnPR_ADDEDChanging(System.Nullable<System.DateTime> value);
    partial void OnPR_ADDEDChanged();
    partial void OnPR_LAST_MODIFIEDChanging(System.Nullable<System.DateTime> value);
    partial void OnPR_LAST_MODIFIEDChanged();
    partial void OnPR_IS_ACTIVEChanging(System.Nullable<bool> value);
    partial void OnPR_IS_ACTIVEChanged();
    partial void OnPR_USEDChanging(System.Nullable<bool> value);
    partial void OnPR_USEDChanged();
    #endregion
		
		public PR_Product()
		{
			this._IE_InvoicesItems = new EntitySet<IE_InvoicesItem>(new Action<IE_InvoicesItem>(this.attach_IE_InvoicesItems), new Action<IE_InvoicesItem>(this.detach_IE_InvoicesItems));
			this._OE_OrderItems = new EntitySet<OE_OrderItem>(new Action<OE_OrderItem>(this.attach_OE_OrderItems), new Action<OE_OrderItem>(this.detach_OE_OrderItems));
			this._PC_ProductCategory = default(EntityRef<PC_ProductCategory>);
			this._QT_QuantityType = default(EntityRef<QT_QuantityType>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PR_ID
		{
			get
			{
				return this._PR_ID;
			}
			set
			{
				if ((this._PR_ID != value))
				{
					this.OnPR_IDChanging(value);
					this.SendPropertyChanging();
					this._PR_ID = value;
					this.SendPropertyChanged("PR_ID");
					this.OnPR_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_PC_ID", DbType="Int NOT NULL")]
		public int PR_PC_ID
		{
			get
			{
				return this._PR_PC_ID;
			}
			set
			{
				if ((this._PR_PC_ID != value))
				{
					if (this._PC_ProductCategory.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPR_PC_IDChanging(value);
					this.SendPropertyChanging();
					this._PR_PC_ID = value;
					this.SendPropertyChanged("PR_PC_ID");
					this.OnPR_PC_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_QT_ID", DbType="Int NOT NULL")]
		public int PR_QT_ID
		{
			get
			{
				return this._PR_QT_ID;
			}
			set
			{
				if ((this._PR_QT_ID != value))
				{
					if (this._QT_QuantityType.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPR_QT_IDChanging(value);
					this.SendPropertyChanging();
					this._PR_QT_ID = value;
					this.SendPropertyChanged("PR_QT_ID");
					this.OnPR_QT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_NAME", DbType="NVarChar(50)")]
		public string PR_NAME
		{
			get
			{
				return this._PR_NAME;
			}
			set
			{
				if ((this._PR_NAME != value))
				{
					this.OnPR_NAMEChanging(value);
					this.SendPropertyChanging();
					this._PR_NAME = value;
					this.SendPropertyChanged("PR_NAME");
					this.OnPR_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_DEPOT_QUANTITY", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> PR_DEPOT_QUANTITY
		{
			get
			{
				return this._PR_DEPOT_QUANTITY;
			}
			set
			{
				if ((this._PR_DEPOT_QUANTITY != value))
				{
					this.OnPR_DEPOT_QUANTITYChanging(value);
					this.SendPropertyChanging();
					this._PR_DEPOT_QUANTITY = value;
					this.SendPropertyChanged("PR_DEPOT_QUANTITY");
					this.OnPR_DEPOT_QUANTITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_UNIT_PRICE", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> PR_UNIT_PRICE
		{
			get
			{
				return this._PR_UNIT_PRICE;
			}
			set
			{
				if ((this._PR_UNIT_PRICE != value))
				{
					this.OnPR_UNIT_PRICEChanging(value);
					this.SendPropertyChanging();
					this._PR_UNIT_PRICE = value;
					this.SendPropertyChanged("PR_UNIT_PRICE");
					this.OnPR_UNIT_PRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_ADDED", DbType="DateTime")]
		public System.Nullable<System.DateTime> PR_ADDED
		{
			get
			{
				return this._PR_ADDED;
			}
			set
			{
				if ((this._PR_ADDED != value))
				{
					this.OnPR_ADDEDChanging(value);
					this.SendPropertyChanging();
					this._PR_ADDED = value;
					this.SendPropertyChanged("PR_ADDED");
					this.OnPR_ADDEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_LAST_MODIFIED", DbType="DateTime")]
		public System.Nullable<System.DateTime> PR_LAST_MODIFIED
		{
			get
			{
				return this._PR_LAST_MODIFIED;
			}
			set
			{
				if ((this._PR_LAST_MODIFIED != value))
				{
					this.OnPR_LAST_MODIFIEDChanging(value);
					this.SendPropertyChanging();
					this._PR_LAST_MODIFIED = value;
					this.SendPropertyChanged("PR_LAST_MODIFIED");
					this.OnPR_LAST_MODIFIEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_IS_ACTIVE", DbType="Bit")]
		public System.Nullable<bool> PR_IS_ACTIVE
		{
			get
			{
				return this._PR_IS_ACTIVE;
			}
			set
			{
				if ((this._PR_IS_ACTIVE != value))
				{
					this.OnPR_IS_ACTIVEChanging(value);
					this.SendPropertyChanging();
					this._PR_IS_ACTIVE = value;
					this.SendPropertyChanged("PR_IS_ACTIVE");
					this.OnPR_IS_ACTIVEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_USED", DbType="Bit")]
		public System.Nullable<bool> PR_USED
		{
			get
			{
				return this._PR_USED;
			}
			set
			{
				if ((this._PR_USED != value))
				{
					this.OnPR_USEDChanging(value);
					this.SendPropertyChanging();
					this._PR_USED = value;
					this.SendPropertyChanged("PR_USED");
					this.OnPR_USEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PR_Product_IE_InvoicesItem", Storage="_IE_InvoicesItems", ThisKey="PR_ID", OtherKey="IE_PR_ID")]
		public EntitySet<IE_InvoicesItem> IE_InvoicesItems
		{
			get
			{
				return this._IE_InvoicesItems;
			}
			set
			{
				this._IE_InvoicesItems.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PR_Product_OE_OrderItem", Storage="_OE_OrderItems", ThisKey="PR_ID", OtherKey="OE_PR_ID")]
		public EntitySet<OE_OrderItem> OE_OrderItems
		{
			get
			{
				return this._OE_OrderItems;
			}
			set
			{
				this._OE_OrderItems.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PC_ProductCategory_PR_Product", Storage="_PC_ProductCategory", ThisKey="PR_PC_ID", OtherKey="PC_ID", IsForeignKey=true)]
		public PC_ProductCategory PC_ProductCategory
		{
			get
			{
				return this._PC_ProductCategory.Entity;
			}
			set
			{
				PC_ProductCategory previousValue = this._PC_ProductCategory.Entity;
				if (((previousValue != value) 
							|| (this._PC_ProductCategory.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PC_ProductCategory.Entity = null;
						previousValue.PR_Products.Remove(this);
					}
					this._PC_ProductCategory.Entity = value;
					if ((value != null))
					{
						value.PR_Products.Add(this);
						this._PR_PC_ID = value.PC_ID;
					}
					else
					{
						this._PR_PC_ID = default(int);
					}
					this.SendPropertyChanged("PC_ProductCategory");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QT_QuantityType_PR_Product", Storage="_QT_QuantityType", ThisKey="PR_QT_ID", OtherKey="QT_ID", IsForeignKey=true)]
		public QT_QuantityType QT_QuantityType
		{
			get
			{
				return this._QT_QuantityType.Entity;
			}
			set
			{
				QT_QuantityType previousValue = this._QT_QuantityType.Entity;
				if (((previousValue != value) 
							|| (this._QT_QuantityType.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QT_QuantityType.Entity = null;
						previousValue.PR_Products.Remove(this);
					}
					this._QT_QuantityType.Entity = value;
					if ((value != null))
					{
						value.PR_Products.Add(this);
						this._PR_QT_ID = value.QT_ID;
					}
					else
					{
						this._PR_QT_ID = default(int);
					}
					this.SendPropertyChanged("QT_QuantityType");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_IE_InvoicesItems(IE_InvoicesItem entity)
		{
			this.SendPropertyChanging();
			entity.PR_Product = this;
		}
		
		private void detach_IE_InvoicesItems(IE_InvoicesItem entity)
		{
			this.SendPropertyChanging();
			entity.PR_Product = null;
		}
		
		private void attach_OE_OrderItems(OE_OrderItem entity)
		{
			this.SendPropertyChanging();
			entity.PR_Product = this;
		}
		
		private void detach_OE_OrderItems(OE_OrderItem entity)
		{
			this.SendPropertyChanging();
			entity.PR_Product = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QT_QuantityTypes")]
	public partial class QT_QuantityType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _QT_ID;
		
		private string _QT_NAME;
		
		private EntitySet<PR_Product> _PR_Products;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnQT_IDChanging(int value);
    partial void OnQT_IDChanged();
    partial void OnQT_NAMEChanging(string value);
    partial void OnQT_NAMEChanged();
    #endregion
		
		public QT_QuantityType()
		{
			this._PR_Products = new EntitySet<PR_Product>(new Action<PR_Product>(this.attach_PR_Products), new Action<PR_Product>(this.detach_PR_Products));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QT_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int QT_ID
		{
			get
			{
				return this._QT_ID;
			}
			set
			{
				if ((this._QT_ID != value))
				{
					this.OnQT_IDChanging(value);
					this.SendPropertyChanging();
					this._QT_ID = value;
					this.SendPropertyChanged("QT_ID");
					this.OnQT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QT_NAME", DbType="NVarChar(50)")]
		public string QT_NAME
		{
			get
			{
				return this._QT_NAME;
			}
			set
			{
				if ((this._QT_NAME != value))
				{
					this.OnQT_NAMEChanging(value);
					this.SendPropertyChanging();
					this._QT_NAME = value;
					this.SendPropertyChanged("QT_NAME");
					this.OnQT_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QT_QuantityType_PR_Product", Storage="_PR_Products", ThisKey="QT_ID", OtherKey="PR_QT_ID")]
		public EntitySet<PR_Product> PR_Products
		{
			get
			{
				return this._PR_Products;
			}
			set
			{
				this._PR_Products.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PR_Products(PR_Product entity)
		{
			this.SendPropertyChanging();
			entity.QT_QuantityType = this;
		}
		
		private void detach_PR_Products(PR_Product entity)
		{
			this.SendPropertyChanging();
			entity.QT_QuantityType = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SP_Spedition")]
	public partial class SP_Spedition : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SP_ID;
		
		private string _SP_NAME;
		
		private EntitySet<IN_Invoice> _IN_Invoices;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSP_IDChanging(int value);
    partial void OnSP_IDChanged();
    partial void OnSP_NAMEChanging(string value);
    partial void OnSP_NAMEChanged();
    #endregion
		
		public SP_Spedition()
		{
			this._IN_Invoices = new EntitySet<IN_Invoice>(new Action<IN_Invoice>(this.attach_IN_Invoices), new Action<IN_Invoice>(this.detach_IN_Invoices));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SP_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SP_ID
		{
			get
			{
				return this._SP_ID;
			}
			set
			{
				if ((this._SP_ID != value))
				{
					this.OnSP_IDChanging(value);
					this.SendPropertyChanging();
					this._SP_ID = value;
					this.SendPropertyChanged("SP_ID");
					this.OnSP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SP_NAME", DbType="NVarChar(50)")]
		public string SP_NAME
		{
			get
			{
				return this._SP_NAME;
			}
			set
			{
				if ((this._SP_NAME != value))
				{
					this.OnSP_NAMEChanging(value);
					this.SendPropertyChanging();
					this._SP_NAME = value;
					this.SendPropertyChanged("SP_NAME");
					this.OnSP_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SP_Spedition_IN_Invoice", Storage="_IN_Invoices", ThisKey="SP_ID", OtherKey="IN_SP_ID")]
		public EntitySet<IN_Invoice> IN_Invoices
		{
			get
			{
				return this._IN_Invoices;
			}
			set
			{
				this._IN_Invoices.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_IN_Invoices(IN_Invoice entity)
		{
			this.SendPropertyChanging();
			entity.SP_Spedition = this;
		}
		
		private void detach_IN_Invoices(IN_Invoice entity)
		{
			this.SendPropertyChanging();
			entity.SP_Spedition = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SU_Suppliers")]
	public partial class SU_Supplier : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SU_ID;
		
		private string _SU_NAME;
		
		private string _SU_STREET;
		
		private string _SU_POST_CODE;
		
		private string _SU_TOWN;
		
		private string _SU_PHONE;
		
		private System.Nullable<System.DateTime> _SU_ADDED;
		
		private System.Nullable<System.DateTime> _SU_LAST_MODIFIED;
		
		private EntitySet<OR_Order> _OR_Orders;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSU_IDChanging(int value);
    partial void OnSU_IDChanged();
    partial void OnSU_NAMEChanging(string value);
    partial void OnSU_NAMEChanged();
    partial void OnSU_STREETChanging(string value);
    partial void OnSU_STREETChanged();
    partial void OnSU_POST_CODEChanging(string value);
    partial void OnSU_POST_CODEChanged();
    partial void OnSU_TOWNChanging(string value);
    partial void OnSU_TOWNChanged();
    partial void OnSU_PHONEChanging(string value);
    partial void OnSU_PHONEChanged();
    partial void OnSU_ADDEDChanging(System.Nullable<System.DateTime> value);
    partial void OnSU_ADDEDChanged();
    partial void OnSU_LAST_MODIFIEDChanging(System.Nullable<System.DateTime> value);
    partial void OnSU_LAST_MODIFIEDChanged();
    #endregion
		
		public SU_Supplier()
		{
			this._OR_Orders = new EntitySet<OR_Order>(new Action<OR_Order>(this.attach_OR_Orders), new Action<OR_Order>(this.detach_OR_Orders));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SU_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SU_ID
		{
			get
			{
				return this._SU_ID;
			}
			set
			{
				if ((this._SU_ID != value))
				{
					this.OnSU_IDChanging(value);
					this.SendPropertyChanging();
					this._SU_ID = value;
					this.SendPropertyChanged("SU_ID");
					this.OnSU_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SU_NAME", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SU_NAME
		{
			get
			{
				return this._SU_NAME;
			}
			set
			{
				if ((this._SU_NAME != value))
				{
					this.OnSU_NAMEChanging(value);
					this.SendPropertyChanging();
					this._SU_NAME = value;
					this.SendPropertyChanged("SU_NAME");
					this.OnSU_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SU_STREET", DbType="NVarChar(100)")]
		public string SU_STREET
		{
			get
			{
				return this._SU_STREET;
			}
			set
			{
				if ((this._SU_STREET != value))
				{
					this.OnSU_STREETChanging(value);
					this.SendPropertyChanging();
					this._SU_STREET = value;
					this.SendPropertyChanged("SU_STREET");
					this.OnSU_STREETChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SU_POST_CODE", DbType="NVarChar(10)")]
		public string SU_POST_CODE
		{
			get
			{
				return this._SU_POST_CODE;
			}
			set
			{
				if ((this._SU_POST_CODE != value))
				{
					this.OnSU_POST_CODEChanging(value);
					this.SendPropertyChanging();
					this._SU_POST_CODE = value;
					this.SendPropertyChanged("SU_POST_CODE");
					this.OnSU_POST_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SU_TOWN", DbType="NVarChar(50)")]
		public string SU_TOWN
		{
			get
			{
				return this._SU_TOWN;
			}
			set
			{
				if ((this._SU_TOWN != value))
				{
					this.OnSU_TOWNChanging(value);
					this.SendPropertyChanging();
					this._SU_TOWN = value;
					this.SendPropertyChanged("SU_TOWN");
					this.OnSU_TOWNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SU_PHONE", DbType="NVarChar(15)")]
		public string SU_PHONE
		{
			get
			{
				return this._SU_PHONE;
			}
			set
			{
				if ((this._SU_PHONE != value))
				{
					this.OnSU_PHONEChanging(value);
					this.SendPropertyChanging();
					this._SU_PHONE = value;
					this.SendPropertyChanged("SU_PHONE");
					this.OnSU_PHONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SU_ADDED", DbType="DateTime")]
		public System.Nullable<System.DateTime> SU_ADDED
		{
			get
			{
				return this._SU_ADDED;
			}
			set
			{
				if ((this._SU_ADDED != value))
				{
					this.OnSU_ADDEDChanging(value);
					this.SendPropertyChanging();
					this._SU_ADDED = value;
					this.SendPropertyChanged("SU_ADDED");
					this.OnSU_ADDEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SU_LAST_MODIFIED", DbType="DateTime")]
		public System.Nullable<System.DateTime> SU_LAST_MODIFIED
		{
			get
			{
				return this._SU_LAST_MODIFIED;
			}
			set
			{
				if ((this._SU_LAST_MODIFIED != value))
				{
					this.OnSU_LAST_MODIFIEDChanging(value);
					this.SendPropertyChanging();
					this._SU_LAST_MODIFIED = value;
					this.SendPropertyChanged("SU_LAST_MODIFIED");
					this.OnSU_LAST_MODIFIEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SU_Supplier_OR_Order", Storage="_OR_Orders", ThisKey="SU_ID", OtherKey="OR_SU_ID")]
		public EntitySet<OR_Order> OR_Orders
		{
			get
			{
				return this._OR_Orders;
			}
			set
			{
				this._OR_Orders.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_OR_Orders(OR_Order entity)
		{
			this.SendPropertyChanging();
			entity.SU_Supplier = this;
		}
		
		private void detach_OR_Orders(OR_Order entity)
		{
			this.SendPropertyChanging();
			entity.SU_Supplier = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.US_Users")]
	public partial class US_User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _US_ID;
		
		private System.Nullable<int> _US_WO_ID;
		
		private string _US_USERNAME;
		
		private string _US_PASSWORD;
		
		private bool _US_IS_ADMIN;
		
		private bool _US_IS_CASHIER;
		
		private bool _US_IS_STOREKEEPER;
		
		private System.Nullable<System.DateTime> _US_ADDED;
		
		private System.Nullable<System.DateTime> _US_LAST_MODIFIED;
		
		private EntityRef<WO_Worker> _WO_Worker;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUS_IDChanging(int value);
    partial void OnUS_IDChanged();
    partial void OnUS_WO_IDChanging(System.Nullable<int> value);
    partial void OnUS_WO_IDChanged();
    partial void OnUS_USERNAMEChanging(string value);
    partial void OnUS_USERNAMEChanged();
    partial void OnUS_PASSWORDChanging(string value);
    partial void OnUS_PASSWORDChanged();
    partial void OnUS_IS_ADMINChanging(bool value);
    partial void OnUS_IS_ADMINChanged();
    partial void OnUS_IS_CASHIERChanging(bool value);
    partial void OnUS_IS_CASHIERChanged();
    partial void OnUS_IS_STOREKEEPERChanging(bool value);
    partial void OnUS_IS_STOREKEEPERChanged();
    partial void OnUS_ADDEDChanging(System.Nullable<System.DateTime> value);
    partial void OnUS_ADDEDChanged();
    partial void OnUS_LAST_MODIFIEDChanging(System.Nullable<System.DateTime> value);
    partial void OnUS_LAST_MODIFIEDChanged();
    #endregion
		
		public US_User()
		{
			this._WO_Worker = default(EntityRef<WO_Worker>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_US_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int US_ID
		{
			get
			{
				return this._US_ID;
			}
			set
			{
				if ((this._US_ID != value))
				{
					this.OnUS_IDChanging(value);
					this.SendPropertyChanging();
					this._US_ID = value;
					this.SendPropertyChanged("US_ID");
					this.OnUS_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_US_WO_ID", DbType="Int")]
		public System.Nullable<int> US_WO_ID
		{
			get
			{
				return this._US_WO_ID;
			}
			set
			{
				if ((this._US_WO_ID != value))
				{
					if (this._WO_Worker.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUS_WO_IDChanging(value);
					this.SendPropertyChanging();
					this._US_WO_ID = value;
					this.SendPropertyChanged("US_WO_ID");
					this.OnUS_WO_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_US_USERNAME", DbType="NVarChar(50)")]
		public string US_USERNAME
		{
			get
			{
				return this._US_USERNAME;
			}
			set
			{
				if ((this._US_USERNAME != value))
				{
					this.OnUS_USERNAMEChanging(value);
					this.SendPropertyChanging();
					this._US_USERNAME = value;
					this.SendPropertyChanged("US_USERNAME");
					this.OnUS_USERNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_US_PASSWORD", DbType="NVarChar(50)")]
		public string US_PASSWORD
		{
			get
			{
				return this._US_PASSWORD;
			}
			set
			{
				if ((this._US_PASSWORD != value))
				{
					this.OnUS_PASSWORDChanging(value);
					this.SendPropertyChanging();
					this._US_PASSWORD = value;
					this.SendPropertyChanged("US_PASSWORD");
					this.OnUS_PASSWORDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_US_IS_ADMIN", DbType="Bit NOT NULL")]
		public bool US_IS_ADMIN
		{
			get
			{
				return this._US_IS_ADMIN;
			}
			set
			{
				if ((this._US_IS_ADMIN != value))
				{
					this.OnUS_IS_ADMINChanging(value);
					this.SendPropertyChanging();
					this._US_IS_ADMIN = value;
					this.SendPropertyChanged("US_IS_ADMIN");
					this.OnUS_IS_ADMINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_US_IS_CASHIER", DbType="Bit NOT NULL")]
		public bool US_IS_CASHIER
		{
			get
			{
				return this._US_IS_CASHIER;
			}
			set
			{
				if ((this._US_IS_CASHIER != value))
				{
					this.OnUS_IS_CASHIERChanging(value);
					this.SendPropertyChanging();
					this._US_IS_CASHIER = value;
					this.SendPropertyChanged("US_IS_CASHIER");
					this.OnUS_IS_CASHIERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_US_IS_STOREKEEPER", DbType="Bit NOT NULL")]
		public bool US_IS_STOREKEEPER
		{
			get
			{
				return this._US_IS_STOREKEEPER;
			}
			set
			{
				if ((this._US_IS_STOREKEEPER != value))
				{
					this.OnUS_IS_STOREKEEPERChanging(value);
					this.SendPropertyChanging();
					this._US_IS_STOREKEEPER = value;
					this.SendPropertyChanged("US_IS_STOREKEEPER");
					this.OnUS_IS_STOREKEEPERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_US_ADDED", DbType="DateTime")]
		public System.Nullable<System.DateTime> US_ADDED
		{
			get
			{
				return this._US_ADDED;
			}
			set
			{
				if ((this._US_ADDED != value))
				{
					this.OnUS_ADDEDChanging(value);
					this.SendPropertyChanging();
					this._US_ADDED = value;
					this.SendPropertyChanged("US_ADDED");
					this.OnUS_ADDEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_US_LAST_MODIFIED", DbType="DateTime")]
		public System.Nullable<System.DateTime> US_LAST_MODIFIED
		{
			get
			{
				return this._US_LAST_MODIFIED;
			}
			set
			{
				if ((this._US_LAST_MODIFIED != value))
				{
					this.OnUS_LAST_MODIFIEDChanging(value);
					this.SendPropertyChanging();
					this._US_LAST_MODIFIED = value;
					this.SendPropertyChanged("US_LAST_MODIFIED");
					this.OnUS_LAST_MODIFIEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WO_Worker_US_User", Storage="_WO_Worker", ThisKey="US_WO_ID", OtherKey="WO_ID", IsForeignKey=true)]
		public WO_Worker WO_Worker
		{
			get
			{
				return this._WO_Worker.Entity;
			}
			set
			{
				WO_Worker previousValue = this._WO_Worker.Entity;
				if (((previousValue != value) 
							|| (this._WO_Worker.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._WO_Worker.Entity = null;
						previousValue.US_Users.Remove(this);
					}
					this._WO_Worker.Entity = value;
					if ((value != null))
					{
						value.US_Users.Add(this);
						this._US_WO_ID = value.WO_ID;
					}
					else
					{
						this._US_WO_ID = default(Nullable<int>);
					}
					this.SendPropertyChanged("WO_Worker");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
